/**
 * Generate `src/editor/icons.css` from the Untitled UI icon SVGs.
 *
 * Icons: Untitled UI free icons (https://www.untitledui.com/free-icons),
 * © Untitled UI, used under their free license (see THIRD-PARTY-NOTICES.md;
 * full terms at https://www.untitledui.com/license). Source SVGs are
 * cloned (gitignored) at `reference-docs/untitled-ui-icons`; the
 * generated CSS embeds only the glyphs we use as data-URL masks so the
 * committed app is self-contained. Re-run with
 * `node scripts/gen-icons.mjs` after editing the MAP below.
 *
 * The icon system is theme-friendly + runtime-toggleable: each icon is
 * a `<span class="pmd-icon pmd-icon-NAME">` painted in `currentColor`
 * via a mask. `:root[data-icons="modern"]` (default) uses the SVG;
 * `:root[data-icons="classic"]` falls back to the original emoji/glyph
 * via `::before`, so the whole app re-skins by flipping one attribute.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const ICON_DIR = join(here, '..', 'reference-docs', 'untitled-ui-icons', 'icons');
const OUT = join(here, '..', 'src', 'editor', 'icons.css');

/** pmd icon name → { svg: Untitled UI filename, glyph: classic emoji/text } */
const MAP = {
  open: { svg: 'folder', glyph: '📂' },
  new: { svg: 'file-plus-01', glyph: '🆕' },
  save: { svg: 'save-01', glyph: '💾' },
  autosave: { svg: 'clock-refresh', glyph: '⏱' },
  'paragraph-integrity': { svg: 'pilcrow-02', glyph: '¶' },
  mic: { svg: 'microphone-01', glyph: '🎤' },
  'speech-mark': { svg: 'pin-02', glyph: '📌' },
  'send-cursor': { svg: 'corner-down-right', glyph: '➤' },
  'send-end': { svg: 'arrow-down', glyph: '⤓' },
  search: { svg: 'search-md', glyph: '🔍' },
  tag: { svg: 'tag-01', glyph: '🏷️' },
  manage: { svg: 'book-closed', glyph: '🗂️' },
  add: { svg: 'plus', glyph: '➕' },
  highlight: { svg: 'edit-05', glyph: '✎' },
  shading: { svg: 'paint-pour', glyph: '🪣' },
  image: { svg: 'image-01', glyph: '🖼' },
  settings: { svg: 'settings-01', glyph: '⚙' },
  home: { svg: 'home-line', glyph: '🏠' },
  close: { svg: 'x-close', glyph: '×' },
  plus: { svg: 'plus', glyph: '+' },
  reset: { svg: 'refresh-ccw-01', glyph: '↺' },
  'arrow-up': { svg: 'arrow-up', glyph: '↑' },
  'arrow-down': { svg: 'arrow-down', glyph: '↓' },
  'chevron-up': { svg: 'chevron-up', glyph: '▴' },
  'chevron-down': { svg: 'chevron-down', glyph: '▾' },
  'chevron-left': { svg: 'chevron-left', glyph: '◀' },
  'chevron-right': { svg: 'chevron-right', glyph: '▶' },
  expand: { svg: 'maximize-01', glyph: '⛶' },
  minus: { svg: 'minus', glyph: '−' },
  'read-mode': { svg: 'eye', glyph: '👁' },
  'nav-toggle': { svg: 'menu-02', glyph: '☰' },
  comments: { svg: 'message-square-01', glyph: '💬' },
  shortcuts: { svg: 'keyboard-01', glyph: '📖' },
  timer: { svg: 'clock-stopwatch', glyph: '⏱' },
  link: { svg: 'link-01', glyph: '🔗' },
  flashcard: { svg: 'graduation-hat-02', glyph: '🎓' },
  note: { svg: 'file-02', glyph: '📝' },
  edit: { svg: 'edit-02', glyph: '✎' },
  ai: { svg: 'stars-02', glyph: '✨' },
};

/** SVG → CSS-safe data-URL. Force opaque #000 (mask uses alpha, the
 *  `.pmd-icon` background supplies the real color), strip the size so
 *  it scales to the box, and fully percent-encode. */
function dataUrl(svg) {
  const opaque = svg
    .replace(/currentColor/g, '#000')
    .replace(/\s(width|height)="[^"]*"/g, '');
  return `url("data:image/svg+xml,${encodeURIComponent(opaque)}")`;
}

let css = `/* GENERATED by scripts/gen-icons.mjs — do not edit by hand.
 *
 * Icons: Untitled UI free icons (https://www.untitledui.com/free-icons),
 * © Untitled UI, used under their free license (see THIRD-PARTY-NOTICES.md).
 * Each icon paints in currentColor via a mask; flip :root[data-icons]
 * between "modern" (SVG) and "classic" (original emoji glyph) to re-skin
 * the whole app.
 */

.pmd-icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  flex: 0 0 auto;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--pmd-icon) center / contain no-repeat;
  mask: var(--pmd-icon) center / contain no-repeat;
}

/* Classic: drop the mask + paint, draw the original glyph instead.
 * Release the fixed 1em box so the glyph sizes and centers exactly
 * like the original text node did (some emoji are wider than 1em and
 * were clipping / sitting off-center inside the mask box). */
:root[data-icons="classic"] .pmd-icon {
  background: none;
  -webkit-mask: none;
  mask: none;
  width: auto;
  height: auto;
  vertical-align: baseline;
}
:root[data-icons="classic"] .pmd-icon::before {
  font-style: normal;
  line-height: 1;
}
`;

for (const [name, { svg, glyph }] of Object.entries(MAP)) {
  const file = join(ICON_DIR, `${svg}.svg`);
  const markup = readFileSync(file, 'utf8').trim();
  css += `\n.pmd-icon-${name} { --pmd-icon: ${dataUrl(markup)}; }`;
  css += `\n:root[data-icons="classic"] .pmd-icon-${name}::before { content: "${glyph}"; }\n`;
}

writeFileSync(OUT, css);
console.log(`Wrote ${OUT} (${Object.keys(MAP).length} icons).`);
